:SETUP_PARAMS:
#+TITLE: Muscle Plotter
#+author:Doğa Yüksel
#+OPTIONS: toc:2 date:nil
#+LATEX_CLASS: koma-article
#+LATEX_CLASS_OPTIONS: [a4paper, 12pt]
#+LATEX_HEADER: \usepackage{mathptmx}
#+LATEX_HEADER: \usepackage[scaled=.90]{helvet}
#+LATEX_HEADER: \usepackage{courier}
#+LATEX_HEADER: \setkomafont{disposition}{\sffamily}
#+LATEX_HEADER: \setkomafont{subtitle}{\sffamily\Large}
#+LaTeX_HEADER: \usepackage[backend=bibtex,sorting=none]{biblatex}
#+LaTeX_HEADER: \addbibresource{/Users/doga/.org/bibtex/file-1.bib}
:END:

* Abstract
This thesis explores creating an interactive pen and paper application using Electrical Muscle Situmulation. Using this application users can input and get meaningful expressive output from a computer system in a mobile context. Using pen and paper allows the user to engage in cognitavely demanding tasks, such as solving math problems. In the simplest case user inputs the a math function and later muscle-plotter uses user's hand to plot the function. This example is futher expanded into fitting lines through points, finding points of interests etc. These core components are demonstrated in six different applications from different domains.


Muscle-plotter is the first EMS system that produces spacial output, hence is more expresive then earlier systems proposed. In our user study, participants drew random plots within 4mm accuracy and preserved accuracy upto 3 cycles per cm.


* Introduction
** An EMS and Anoto Pen based output system
*** Allows users to a computer solely with pen and paper.
*** An approach that blends the computer and the user

** Motivation
*** A pen based interface is intuitive
*** Interations without screens is the future
*** Interface without an interface is the future

** Constribution
*** Combining pen paper interactions with EMS is novel

** Thesis overview
   This thesis will continue by detailing the Related work in the next chapter. It will then further investigate walkthroughs of the applications developed. In the following chapter, essential components of the implementation of muscle-plotter described. Then finally the thesis is concluded with a discussion.


* Fundamentals and Related Work
** Fundamentals
*** Pen And Paper interactions
**** Pen and paper is an important cognitive tool
**** Acts as an extended memory
**** New technology still mimics the spatial qualities of paper
*** Interactive system are getting smaller
**** Trend is mobile but, we can see further integration
**** EMS is promising in miniturazation


** Related Work
*** State of the art of interactive EMS Systems
    EMS has been around for over half a century. It is mainly used for medical applications. Over several years HCI community has grown interest. Following are several implementations related, worth mentioning.
**** Affordance++
**** Possesed Hand

*** Pen and paper interactions from Research Domain
    Interactive systems based on pen and paper has existed since the dawn of HCI. Muscle-plotter, uses the traces left by the pen held by the user as an output medium. Following are the applications that enhance the pen and paper interactions from the HCI domain.
**** Magnetic table
**** Exosceletons


* Muscle Plotter / Applications
** Overview
   In the simplest case applications for muscle-plotter are initiated by the user. To acomplish a succesful interaction user takes turns with the computer, describes a domain and gets the answers later by applying the required motion. We have implemented several applications in this manner, within several domains and will futher describe them as walkthroughs in the following section.

** Wind tunnel as a simulation / advanced widgets on paper
*** Preparing the workspace / input with pen and recognition

** Math function plots

** Function Plotters in other contexts
*** RC Filter
*** Multiple choise menus
*** Calculating integrals


* Implementation
** Overview
   Current implementation of muscle-plotter uses an Anoto Digitizer Pen & Paper for input and a medically compliant 8-channel portable EMS simulator (from HASOMED) for output. Tracking data from the anoto pen is relayed through a windows machine to the python backend running on a MacOS. Communication between the EMS machine and the python backend takes place throught the custom serial protocol via USB. Current implementation only uses 4 channels of the EMS device. This setup can be miniturized with a hardware similar to the one proposed in Proprioceptive Interaction [cite].


   [system overview figure]


   Following chapter will futher describe the implementation in detail. 

*** Tracking System
    Input to the system is the Anoto Digitizer Pen & Paper that acts as a precise tracker. The paper has patented dot pattern that encodes the location data for each point. The accuracy of the location is quite high where each millimeter has 30 unique points. The camera on the pen scans and returns as long as the pen is pushing to the paper. The angle of the pen influences the quality of tracking. The users are advised to hold the pen at an upright angle. It is important to mention that there is constant delay as the pen captures and analyses this image. This delay has a detrimental effect on the performance of the control loop. It will be futher discussed later in this chapter. In our current implementation, there is a Windows server running the drives provided by the anoto company relaying data to the backend server. The details of these drivers is confined by a Non disclosure agreement.


[figure: EMS machine]


*** EMS Machine and Pad Placement
    EMS machine by HASOMED is capable of generating a situmulation upto 400Hz. In our implementation at a given time two channels are active at most, as a result, each muscle shared the capacity where is situmuated with 200Hz. Futhermore the machine allows to control the amplitude and duty cycle of the signal. The system uses amplitudes ranging from 6mA to 16mA based on calibration results. Duty cycle can range between 20\micro{}s to 500\micro{}s, which provides a very large dynamic range of modulation. Muscle-plotter mainly controls duty cycles to achieve its accuracy. The amplitude is temporarily raised to boost actuation in certain conditions that will be described in the control loop section. 


[figure: hasomed device]


    Medical grade EMS Machine produced by HASOMED is used to sitimulate the arm of the user. In the current implementation 4 channels of the machine is connected to the arm of the user. Each channel is responsible for a different axis of motion. For a right handed setup; flexor carpi radialis moves the pen left, extensor carpi radialis brevis and partially flexor digitorum moves the pen right. Flexor carpi ulnaris is used to push the pen onto the paper, which in return helps to reduce oscilations and slow down. Finally extensor carpi radialis longus lifts the pen up from the paper.


[figure: pads placements left]
[figure: pads placements right]

*** Backend System
    A back-end manages the connection to the EMS machine and the anoto pen.

**** Calibration Program
**** Control Loop
      Fuzzy logic based on strategies orchestrating multiple channels at once.
***** Model of the Human Arm and Travel Strategy
      A low fidelity model describing the human arm as stick held by strings is the basis of the control loop of the muscle-plotter. At a given point flexors and extensors are both exited for a tighter control, which enables muscle-plotter to achive the accuracy it needs.
***** Braking strategy
******* Braking and Keeping on a target
******* Ending an interaction

**** Higher level API for Flow Control
***** canvas elements
***** function definitions
**** Recognition System
     Image recognition -> OpenCV for sketches
     Text recognition -> Tessarect - OCR


* User Study
** Study design
** Verify accuracy of the actuation method
** Sample Curves chosen to understand the limitation


* Discussion
** Consider user study
** Current implementation lacks control that allows actual drawing
** Can't consider as 2D drawing
** Our implementation is a steering action


* Conclusion
** Future Work
*** Evaluate applications 
*** Improve recognition
